language: node_js
notifications:
  email: false
cache:
  directories:
    - node_modules
node_js:
  - "6"
script:
  - npm install
  - ng build --target=production
deploy:
  provider: surge
  domain: whatsthescore.surge.sh
